<?php

/*
 *  Labdoo API
    Copyright (C) 2012  Labdoo team

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
 
function form_labdoo_menu() {
  $items['labdoo_api/form_labdoo'] = array(
    'title' => t('Form Labdoo'),
    'page callback' => 'form_labdoo_info',
    'access callback' => TRUE,
  );

  $items['labdoo_api/form_labdoo/form_laptop'] = array(
    'title' => 'Laptop form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_laptop'),
    'access callback' => TRUE,
    'file' => 'form_labdoo.inc',
  );

  return $items;
}

/**
 * Simple page callback to give feedback to the user about this example.
 */
function form_labdoo_info() {
  return t('The Labdoo form provides a form to make easy to tag the Labdoo laptops');
}

