<?php
/*
 *  Labdoo API
Copyright (C) 2012  Labdoo team

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*/

function facebook_stats_labdoo_menu() {
  // This is the minimum information you can provide for a menu item. This menu
  // item will be created in the default menu (Navigation).
  $items['labdoo_api/ranking'] = array(
    'title' => 'Labdoo - Ranking',
    'page callback' => 'facebook_stats_labdoo_simple',
    'page arguments' => array('facebook stats simple'),
    'access callback' => TRUE,
  );

  return $items;
}

function facebook_stats_labdoo_simple() {
	$limit = 100;
	$query = db_query("SELECT f.id, f.name, f.hits  FROM {facebook_ranking} f ORDER BY f.hits DESC LIMIT %d", $limit);    
	
	$output = "<table border=\"1\">";
	$output.="<tr><th><h3>Likes</h3></th><th><h3>Names</h3></th></tr>";
	while ($row = db_fetch_array($query)) { // this returns the row as an array, use db_fetch_object to get an object
	 	$output.="<tr><td>".$row["hits"]."</td><td>".$row["name"]."</td></tr>";
	}

	 $output.="</table>";
  return '<p align="center">' .$output. '</p>';
}


